export const DATA_VERSION = 17;

export const initialInmuebleData = {
  direccion: "Asoc. Jose Carlos Mariategui Mz 37 Lote 24",
  referencia: "A pasos de Av. La Cultura, Colegio Jorge Chávez y Polideportivo Los Ediles",
  distrito: "Coronel Gregorio Albarracín Lanchipa",
  ciudad: "Tacna, Perú",
  coordenadas: { lat: -18.037808, lng: -70.256515 },
  areaTerrenoM2: 120.5,
  areaConstruidaM2: 384,
  pisos: 4,
  habitaciones: 16,
  banios: 8,
  localComercialM2: 75,
  precioPublicacion: 195000,
  precioNotaAclaratoria: "En revisión según nuevas publicaciones del mercado (análisis: Dic 2025)",
  estadoVenta: "Activo",
  descripcionGeneral: "Inmueble de 4 pisos con estructura antisísmica y planos de arquitectura e ingeniería. Ideal para hotel, clínica, oficinas, academia o renta. Trato directo con propietario, sin comisiones inmobiliarias. Documentación en regla, inscrito en SUNARP, único dueño.",
  caracteristicasEspeciales: [
    "Construcción antisísmica con planos de arquitectura e ingeniería",
    "Servicio de agua 24 hs: 2 tanques elevados 1,000 L c/u + reservorio subterráneo 2,000 L",
    "Trato directo — sin comisiones inmobiliarias",
    "Inscrito en SUNARP, único propietario",
    "Papeles en regla, listo para notaría",
    "Local comercial 75 m² con visibilidad a la calle",
    "Patio interior / lavandería",
    "Azotea con mirador"
  ],
  distribucionPisos: [
    { id: 1, piso: "1er Piso", areaConstruida: 106.80, descripcion: "Local comercial 75 m² (ideal restaurante, gimnasio, farmacia) + 1 habitación + 1 baño completo + medio baño + patio interior/lavandería" },
    { id: 2, piso: "2do Piso", areaConstruida: 108.10, descripcion: "6 habitaciones simples + 2 baños completos" },
    { id: 3, piso: "3er Piso", areaConstruida: 108.10, descripcion: "6 habitaciones simples + 3 baños completos" },
    { id: 4, piso: "4to Piso / Terraza", areaConstruida: 61.00, descripcion: "3 habitaciones adicionales + 1 baño completo + amplia terraza con zona de lavandería" },
    { id: 5, piso: "Azotea", areaConstruida: 0, descripcion: "2 tanques elevados (1,000 L c/u) + mirador. Agua las 24 hs." }
  ],
  ultimaActualizacion: "2025-12-01",
  notas: "Análisis de mercado realizado en Diciembre 2025. Precio de publicación a confirmar según nuevas comparables."
};

export const initialComparables = [
  // === VENDIDAS / DESLISTADAS (se muestran como X) ===
  {
    id: 1,
    nombre: "Casa Asoc. Fortunato Zora Carbajal",
    referencia: "Mz. B Lt. 27, cerca Plaza Pérez Gamboa y Av. Municipal",
    precio: 165000,
    areaTerrenoM2: 200,
    areaConstruidaM2: 290,
    pisos: 3,
    habitaciones: 9,
    banios: 5,
    medioBanio: 1,
    cocheras: 0,
    descripcion: "Casa de 3 pisos independientes. Primer piso con local comercial. Segundo y tercer piso como departamentos independientes. Construcción sólida.",
    usoIdeal: "Vivienda familiar o inversión inmobiliaria (alquiler por pisos o local)",
    fuente: "ubicasa.pe",
    link: "https://ubicasa.pe/inmuebles/casa-venta-coronel-gregorio-albarrac%C3%ADn-lanchipa--290m2-9-dormitorios-714dc1e3",
    coordenadas: { lat: -18.0345, lng: -70.2520 },
    fechaPublicacion: "2025-12",
    activa: false,
    estado: "Vendida o Deslistada"
  },
  {
    id: 2,
    nombre: "Casa Frente a Parque — C. Las Dalias",
    referencia: "Frente a parque, en esquina, C. Las Dalias, Gregorio Albarracín",
    precio: 205000,
    areaTerrenoM2: 128,
    areaConstruidaM2: 382,
    pisos: null,
    habitaciones: 5,
    banios: 4,
    medioBanio: 1,
    cocheras: 1,
    antiguedad: 10,
    descripcion: "Casa en esquina frente a parque. Sala-comedor, cocina con muebles altos y bajos, cochera, 5 baños, 5 dormitorios.",
    usoIdeal: "Vivienda familiar",
    fuente: "ubicasa.pe",
    link: "https://ubicasa.pe/inmuebles/casa-venta-coronel-gregorio-albarrac%C3%ADn-lanchipa--382.0m2-5-dormitorios-9fe6cb4f",
    coordenadas: { lat: -18.0330, lng: -70.2495 },
    fechaPublicacion: "2025-12",
    activa: false,
    estado: "Vendida o Deslistada"
  },
  // === PUBLICACIONES ACTIVAS (numeradas 1-4 según imagen) ===
  {
    id: 7,
    nombre: "Casa de 3 pisos Esquina",
    referencia: "A 1 cuadra de Av. La Cultura, cerca Parque del Niño y Mercado Santa Rosa",
    precio: 155000,
    precioAnterior: 160000,
    areaTerrenoM2: 120,
    areaConstruidaM2: 247,
    pisos: 3,
    habitaciones: 5,
    banios: 5,
    medioBanio: 0,
    cocheras: 1,
    descripcion: "Casa de 3 pisos con excelente ubicación. 120 m² terreno, +247 m² construidos. Cochera, terraza, zona de lavandería.",
    usoIdeal: "Vivienda familiar o inversión",
    fuente: "Properati",
    link: "https://www.properati.com.pe/detalle/14032-32-b270-c395df8feaf6-19d874a-ba66-7128",
    coordenadas: { lat: -18.043389, lng: -70.254806 },
    fechaPublicacion: "2026-05-01",
    activa: true
  },
  {
    id: 4,
    nombre: "Casa Alfonso Ugarte (Bajó -5000 USD)",
    referencia: "Conj. Hab. Alfonso Ugarte II Etapa, frente Plaza La Floresta, cerca Plaza Pérez Gamboa",
    precio: 140000,
    precioAnterior: 145000,
    areaTerrenoM2: 160,
    areaConstruidaM2: 280,
    pisos: 3,
    habitaciones: 6,
    banios: 3,
    medioBanio: 0,
    cocheras: 1,
    descripcion: "Casa de 3 pisos en esquina. Sin cargas ni gravámenes, título de propiedad, partida registral independiente. Ambiente para tienda con puerta enrollable, garaje, patio lavandería. A 2 cuadras Av. Municipal y Av. Antúnez de Mayolo.",
    usoIdeal: "Vivienda familiar, proyecto comercial o desarrollo de departamentos",
    fuente: "Propietarios Perú",
    link: "https://www.properati.com.pe/detalle/14032-32-fc53-caffdc550b1b-1978de7-8ace-7df6",
    coordenadas: { lat: -18.0391775, lng: -70.2482739 },
    fechaPublicacion: "2026-04-30",
    activa: true
  },
  {
    id: 8,
    nombre: "Inmueble Avenida 4 pisos VIÑANI",
    referencia: "Viñani, Gregorio Albarracín (Properati)",
    precio: 265000,
    areaTerrenoM2: 120,
    areaConstruidaM2: 480,
    pisos: 4,
    habitaciones: 9,
    banios: 6,
    medioBanio: 0,
    cocheras: 0,
    descripcion: "Propiedad diseñada para vivir y alquilar. Local comercial 110 m² + 4 departamentos independientes + espacio adicional en 4to piso.",
    usoIdeal: "Inversión comercial o renta",
    fuente: "Properati",
    link: "https://www.properati.com.pe/detalle/14032-32-fade-8c14351f65e-193c0a3-8eeb-724c",
    coordenadas: { lat: -18.0744267, lng: -70.2631459 },
    fechaPublicacion: "2026-05-01",
    activa: true
  },
  // === REFERENCIAS (sin coordenadas, excluidas del mapa y promedios) ===
  {
    id: 10,
    nombre: "Local Comercial Av. La Cultura",
    referencia: "A media cuadra del Mercado Santa Rosa",
    precio: 325000,
    areaTerrenoM2: 121.48,
    areaConstruidaM2: 218,
    pisos: 2,
    habitaciones: 0,
    banios: 0,
    medioBanio: 0,
    cocheras: 0,
    descripcion: "Propiedad comercial en zona de alto tránsito peatonal y vehicular, ideal para negocio, inversión o desarrollo comercial.",
    usoIdeal: "Tienda comercial, consultorios, oficinas, proyecto de renta",
    fuente: "Ubicasa",
    link: "https://ubicasa.pe/inmuebles/local-comercial-venta-coronel-gregorio-albarrac%C3%ADn-lanchipa--218.0m2-0-dormitorios-c42ded61",
    coordenadas: { lat: -18.043608, lng: -70.256217 },
    fechaPublicacion: "2026-05-12",
    activa: false,
    estado: "Referencia",
    notas: "Solo referencia, distorsiona el precio promedio por ser comercial"
  },
  {
    id: 11,
    nombre: "Casa Av. Humboldt (Referencia)",
    referencia: "A solo una cuadra de la Av. Humboldt",
    precio: 170000,
    areaTerrenoM2: 160,
    areaConstruidaM2: null,
    pisos: 3,
    habitaciones: 7,
    banios: 4,
    medioBanio: 1,
    cocheras: 1,
    descripcion: "Primer nivel: Sala, comedor, local comercial. Segundo: 2 Dptos. Tercer: Lavandería, listos para construir hasta 4 pisos.",
    usoIdeal: "Vivienda multifamiliar o negocio",
    fuente: "Properati",
    link: "https://www.properati.com.pe/detalle/14032-32-93e3-550df7eff8b0-1954d24-955a-7ac5",
    coordenadas: null,
    fechaPublicacion: "2025-02-28",
    activa: false,
    estado: "Referencia",
    notas: "Solo referencia, sin precio por m2 por falta de área construida exacta"
  },
  {
    id: 12,
    nombre: "Casa de 1er piso Esquina (Century 21)",
    referencia: "A 2 cuadras de Av. La Cultura, cerca a colegio Gerardo Arias Copaja y Plaza Las Buganvillas. (Nota: Se asume que el área construida es de 120m² por ser de 1 solo piso)",
    precio: 75000,
    areaTerrenoM2: 120,
    areaConstruidaM2: 120,
    pisos: 1,
    habitaciones: 2,
    banios: 1,
    medioBanio: 0,
    cocheras: 1,
    descripcion: "Casa de 1er piso en esquina. Amplia sala comedor, cocina, 2 dormitorios, 1 baño completo, cochera con patio y área de lavandería. Título inscrito en SUNARP, libre de cargas y gravamen. (Nota: Se asume que el área construida es de 120m² por ser de 1 solo piso)",
    usoIdeal: "Vivienda familiar",
    fuente: "Properati",
    link: "https://www.properati.com.pe/detalle/14032-32-faf2-970da16277dc-19efc94-a111-7096",
    coordenadas: { lat: -18.0528925, lng: -70.2596183 },
    fechaPublicacion: "2026-06-25",
    activa: true
  }
];

export const initialDocumentos = [
  { id: 1, nombre: "Partida registral actualizada (SUNARP)", descripcion: "Certifica titularidad. Obtener en SUNARP o virtualmente. ~S/. 20-30. Vigencia: 30 días.", responsable: "Vendedor", listo: false, fecha: null },
  { id: 2, nombre: "DNI del propietario vigente", descripcion: "Documento de identidad. RENIEC.", responsable: "Vendedor", listo: false, fecha: null },
  { id: 3, nombre: "Autovalúo al día (HR y PU)", descripcion: "Declaración de autoavalúo municipal. Municipalidad de Gregorio Albarracín. Gratuito.", responsable: "Vendedor", listo: false, fecha: null },
  { id: 4, nombre: "Certificado de no adeudo municipal", descripcion: "Sin deudas de arbitrios e impuesto predial. Municipalidad. ~S/. 20-50.", responsable: "Vendedor", listo: false, fecha: null },
  { id: 5, nombre: "Planos de arquitectura e ingeniería", descripcion: "Originales o copias certificadas. Ya disponibles según descripción del inmueble.", responsable: "Vendedor", listo: false, fecha: null },
  { id: 6, nombre: "Título de propiedad original", descripcion: "Escritura pública original.", responsable: "Vendedor", listo: false, fecha: null },
  { id: 7, nombre: "Pago de impuesto predial al día", descripcion: "Recibos de pago. Municipalidad.", responsable: "Vendedor", listo: false, fecha: null },
  { id: 8, nombre: "Declaración jurada de no tener cargas ni hipotecas", descripcion: "Preparada por abogado/notario.", responsable: "Vendedor", listo: false, fecha: null },
  { id: 9, nombre: "Certificado de parámetros urbanísticos", descripcion: "Municipalidad Gregorio Albarracín. ~S/. 50-100.", responsable: "Vendedor", listo: false, fecha: null },
  { id: 10, nombre: "Minuta de compraventa", descripcion: "Preparada por abogado. ~S/. 200-500.", responsable: "Notaría", listo: false, fecha: null },
  { id: 11, nombre: "Escritura pública de compraventa", descripcion: "La notaría la eleva a escritura pública.", responsable: "Notaría", listo: false, fecha: null },
  { id: 12, nombre: "Inserción en SUNARP", descripcion: "Inscripción de la transferencia. ~S/. 100-200.", responsable: "Notaría", listo: false, fecha: null },
  { id: 13, nombre: "DNI del comprador vigente", descripcion: "Documento de identidad del comprador.", responsable: "Comprador", listo: false, fecha: null },
  { id: 14, nombre: "Constancia de pago de Alcabala (SUNAT)", descripcion: "Comprobante de pago del impuesto. SUNAT.", responsable: "Comprador", listo: false, fecha: null },
  { id: 15, nombre: "Forma de pago acreditada", descripcion: "Transferencia, carta notarial de fondos, etc.", responsable: "Comprador", listo: false, fecha: null }
];

export const initialActividad = [
  { id: 1, fecha: "2025-12-01", tipo: "Publicación", descripcion: "Análisis de mercado inicial realizado. Precio de publicación propuesto: USD 230,000 (~$568/m²). Se relevaron 4 comparables en zona Gregorio Albarracín.", monto: 230000 },
  { id: 2, fecha: "2025-12-01", tipo: "Publicación", descripcion: "Tabla comparativa de precios por m² elaborada. Precio mínimo de mercado: $518/m². Precio publicación inmueble propio: $568/m².", monto: null },
  { id: 3, fecha: "2025-12-01", tipo: "Documento", descripcion: "Verificación de documentación: partida registral y autovalúo al día. Planos de arquitectura e ingeniería disponibles.", monto: null },
  { id: 4, fecha: "2026-04-01", tipo: "Publicación", descripcion: "Nueva revisión de mercado. Se detectan nuevas publicaciones en zona: Casa Century 21 Alfonso Ugarte ($80,000 / $800/m²). Precio de venta en revisión.", monto: null },
  { id: 5, fecha: "2026-04-30", tipo: "Publicación", descripcion: "Actualización de mercado: La Publicación 4 bajó de $145,000 a $140,000. La Publicación 1 (Zora Carbajal) ya no está disponible, se marca como vendida.", monto: null },
  { id: 6, fecha: "2026-04-30", tipo: "Publicación", descripcion: "Actualización de mercado: La Publicación 2 (C. Las Dalias) también ha sido deslistada o vendida. Se actualiza el estado de las publicaciones 1 y 2.", monto: null },
  { id: 7, fecha: "2026-05-01", tipo: "Publicación", descripcion: "Nueva publicación detectada en Properati: Casa de 3 pisos en esquina ($170,000 / $688/m²). Se agrega al análisis comparativo.", monto: null },
  { id: 8, fecha: "2026-05-01", tipo: "Publicación", descripcion: "Nueva publicación detectada en Properati: Inmueble 4 pisos en Viñani ($265,000 / $552/m²). Ubicación en avenida estratégica.", monto: null },
  { id: 9, fecha: "2026-05-01", tipo: "Publicación", descripcion: "Limpieza de comparables: Se eliminan las publicaciones 3, 5 y 6 por considerarse no relevantes o desactualizadas.", monto: null }
];
